const { getDb } = require('../../lib/db');
const { verifyAdmin } = require('../../lib/auth');
const { sendMessage, sendPhoto } = require('../../lib/telegram');

module.exports = async (req, res) => {
  try {
    // initData comes as a query param on GET/DELETE, or in the JSON body on POST/PUT
    const initData = req.method === 'GET' || req.method === 'DELETE' ? req.query.initData : req.body.initData;
    const admin = verifyAdmin(initData);
    if (!admin) return res.status(401).json({ ok: false, error: 'unauthorized' });

    const db = await getDb();
    const entity = req.query.entity; // 'video' | 'task' | 'message'

    // ---------------- VIDEO: publish using the code generated by webhook.js ----------------
    if (entity === 'video' && req.method === 'POST') {
      const { title, thumbnail, code, categoryIds, includeInAll } = req.body;
      if (!title || !thumbnail || !code) {
        return res.status(400).json({ ok: false, error: 'missing_fields' });
      }

      const pending = await db.collection('pendingUploads').findOne({ code, used: false });
      if (!pending) return res.status(404).json({ ok: false, error: 'invalid_or_used_code' });

      const result = await db.collection('videos').insertOne({
        title,
        thumbnail,
        sourceChatId: pending.sourceChatId,       // admin's own DM chat with the bot
        sourceMessageId: pending.sourceMessageId,  // no channel involved anywhere
        unlockCount: 0,
        // categoryIds: which extra sections (e.g. "Bangla Movies") this video shows in.
        // includeInAll: shows in the "All" tab by default; admin can uncheck it to
        // keep a video ONLY inside its specific category sections.
        categoryIds: Array.isArray(categoryIds) ? categoryIds : [],
        includeInAll: includeInAll !== false,
        createdAt: new Date()
      });

      await db.collection('pendingUploads').updateOne({ code }, { $set: { used: true } });

      return res.status(200).json({ ok: true, videoId: result.insertedId });
    }

    if (entity === 'video' && req.method === 'DELETE') {
      const { ObjectId } = require('mongodb');
      await db.collection('videos').deleteOne({ _id: new ObjectId(req.query.id) });
      return res.status(200).json({ ok: true });
    }

    if (entity === 'video' && req.method === 'PUT') {
      const { ObjectId } = require('mongodb');
      const { id, title, thumbnail, categoryIds, includeInAll } = req.body;
      const update = { title, thumbnail };
      if (categoryIds !== undefined) update.categoryIds = Array.isArray(categoryIds) ? categoryIds : [];
      if (includeInAll !== undefined) update.includeInAll = includeInAll !== false;
      await db.collection('videos').updateOne(
        { _id: new ObjectId(id) },
        { $set: update }
      );
      return res.status(200).json({ ok: true });
    }

    // ---------------- TASK ----------------
    if (entity === 'task' && req.method === 'POST') {
      const { title, reward, taskType, link, channelId } = req.body;
      if (!title || reward == null || !taskType || !link) {
        return res.status(400).json({ ok: false, error: 'missing_fields' });
      }
      if (taskType === 'verified' && !channelId) {
        return res.status(400).json({ ok: false, error: 'channelId_required_for_verified' });
      }

      const result = await db.collection('tasks').insertOne({
        title, reward: parseFloat(reward), taskType, link, channelId: channelId || null,
        active: true, createdAt: new Date()
      });
      return res.status(200).json({ ok: true, taskId: result.insertedId });
    }

    if (entity === 'task' && req.method === 'DELETE') {
      const { ObjectId } = require('mongodb');
      await db.collection('tasks').updateOne({ _id: new ObjectId(req.query.id) }, { $set: { active: false } });
      return res.status(200).json({ ok: true });
    }

    // ---------------- CATEGORY (e.g. "Bangla Movies", "Hindi Movies") ----------------
    if (entity === 'category' && req.method === 'POST') {
      const { name } = req.body;
      if (!name || !name.trim()) {
        return res.status(400).json({ ok: false, error: 'missing_name' });
      }
      try {
        const result = await db.collection('categories').insertOne({ name: name.trim(), createdAt: new Date() });
        return res.status(200).json({ ok: true, categoryId: result.insertedId });
      } catch (err) {
        if (err.code === 11000) return res.status(409).json({ ok: false, error: 'duplicate_name' });
        throw err;
      }
    }

    if (entity === 'category' && req.method === 'GET') {
      const categories = await db.collection('categories').find({}).sort({ createdAt: 1 }).toArray();
      return res.status(200).json({ ok: true, categories });
    }

    if (entity === 'category' && req.method === 'DELETE') {
      const { ObjectId } = require('mongodb');
      const id = req.query.id;
      await db.collection('categories').deleteOne({ _id: new ObjectId(id) });
      // Keep video data clean - pull the deleted category out of every video that had it.
      await db.collection('videos').updateMany({}, { $pull: { categoryIds: id } });
      return res.status(200).json({ ok: true });
    }

    // ---------------- WITHDRAWALS: list + approve/reject ----------------
    if (entity === 'withdrawal' && req.method === 'GET') {
      const statusFilter = req.query.status; // optional: 'pending' | 'approved' | 'rejected'
      const query = statusFilter ? { status: statusFilter } : {};
      const withdrawals = await db.collection('withdrawals').find(query).sort({ createdAt: -1 }).toArray();

      // Attach the requester's name for display.
      const userIds = [...new Set(withdrawals.map(w => w.userId))];
      const users = await db.collection('users').find({ telegramId: { $in: userIds } }).toArray();
      const userMap = Object.fromEntries(users.map(u => [u.telegramId, u]));

      return res.status(200).json({
        ok: true,
        withdrawals: withdrawals.map(w => ({
          id: w._id,
          userId: w.userId,
          userName: userMap[w.userId]
            ? `${userMap[w.userId].firstName || ''}${userMap[w.userId].username ? ' (@' + userMap[w.userId].username + ')' : ''}`
            : w.userId,
          amount: w.amount,
          method: w.method,
          accountNumber: w.accountNumber,
          status: w.status,
          createdAt: w.createdAt
        }))
      });
    }

    if (entity === 'withdrawal' && req.method === 'POST') {
      const { ObjectId } = require('mongodb');
      const { id, action } = req.body;
      if (!id || !['approve', 'reject'].includes(action)) {
        return res.status(400).json({ ok: false, error: 'missing_fields' });
      }

      const withdrawal = await db.collection('withdrawals').findOne({ _id: new ObjectId(id) });
      if (!withdrawal) return res.status(404).json({ ok: false, error: 'not_found' });
      if (withdrawal.status !== 'pending') {
        return res.status(409).json({ ok: false, error: 'already_decided' });
      }

      if (action === 'approve') {
        await db.collection('withdrawals').updateOne(
          { _id: withdrawal._id },
          { $set: { status: 'approved', updatedAt: new Date() } }
        );
        await sendMessage(
          withdrawal.userId,
          `✅ আপনার <b>${withdrawal.amount} DHC</b> withdraw request (${withdrawal.method}) approve হয়েছে। টাকা আপনার ${withdrawal.method === 'bkash' ? 'Bkash' : 'Nagad'} নাম্বারে পাঠানো হচ্ছে।`
        );
      } else {
        await db.collection('withdrawals').updateOne(
          { _id: withdrawal._id },
          { $set: { status: 'rejected', updatedAt: new Date() } }
        );
        // Refund the held balance since the request didn't go through.
        await db.collection('users').updateOne(
          { telegramId: withdrawal.userId },
          { $inc: { balance: withdrawal.amount } }
        );
        await sendMessage(
          withdrawal.userId,
          `❌ আপনার <b>${withdrawal.amount} DHC</b> withdraw request reject হয়েছে। আপনার balance-এ ${withdrawal.amount} DHC ফেরত দেওয়া হয়েছে।`
        );
      }

      return res.status(200).json({ ok: true });
    }

    // ---------------- USER: manually adjust a balance (increase/decrease) ----------------
    if (entity === 'user' && req.method === 'POST') {
      const { telegramId, delta } = req.body;
      const amount = parseFloat(delta);
      if (!telegramId || !amount || isNaN(amount)) {
        return res.status(400).json({ ok: false, error: 'missing_fields' });
      }

      const updatedUser = await db.collection('users').findOneAndUpdate(
        { telegramId: String(telegramId) },
        { $inc: { balance: amount } },
        { returnDocument: 'after' }
      );
      if (!updatedUser) return res.status(404).json({ ok: false, error: 'user_not_found' });

      return res.status(200).json({ ok: true, telegramId: updatedUser.telegramId, newBalance: updatedUser.balance });
    }

    // ---------------- LIST (for admin panel tables) ----------------
    if (entity === 'video' && req.method === 'GET') {
      const videos = await db.collection('videos').find({}).sort({ createdAt: -1 }).toArray();
      return res.status(200).json({ ok: true, videos });
    }
    if (entity === 'task' && req.method === 'GET') {
      const tasks = await db.collection('tasks').find({}).sort({ createdAt: -1 }).toArray();
      return res.status(200).json({ ok: true, tasks });
    }

    // ---------------- CUSTOM MESSAGE TO ONE USER, OR BROADCAST TO ALL ----------------
    // Sends text and/or an image with a single button underneath.
    // - targetId given  -> goes to just that one user.
    // - targetId blank  -> goes to EVERY user in the database (broadcast).
    // - videoId given   -> button opens that video's detail page directly.
    // - videoId blank   -> button opens the app's home page (default APP_URL).
    // The button's label is whatever the admin typed, but it always opens the
    // bot's own Mini App (optionally deep-linked to a video) - never anywhere else.
    if (entity === 'message' && req.method === 'POST') {
      const { targetId, text, imageUrl, buttonText, videoId } = req.body;

      if (!buttonText || (!text && !imageUrl)) {
        return res.status(400).json({ ok: false, error: 'missing_fields' });
      }

      const appUrl = process.env.APP_URL;
      let buttonUrl = appUrl;

      if (videoId) {
        const { ObjectId } = require('mongodb');
        let video;
        try {
          video = await db.collection('videos').findOne({ _id: new ObjectId(videoId) });
        } catch {
          return res.status(400).json({ ok: false, error: 'invalid_video_id' });
        }
        if (!video) return res.status(404).json({ ok: false, error: 'video_not_found' });
        buttonUrl = `${appUrl}?video=${videoId}`;
      }

      const replyMarkup = {
        inline_keyboard: [[
          { text: buttonText, web_app: { url: buttonUrl } }
        ]]
      };

      // ---- Single targeted user ----
      if (targetId) {
        const targetUser = await db.collection('users').findOne({ telegramId: String(targetId) });
        if (!targetUser) {
          return res.status(404).json({ ok: false, error: 'user_not_found' });
        }

        const result = imageUrl
          ? await sendPhoto(targetId, imageUrl, text || '', { reply_markup: replyMarkup })
          : await sendMessage(targetId, text, { reply_markup: replyMarkup });

        if (!result.ok) {
          return res.status(500).json({ ok: false, error: 'send_failed', detail: result.description });
        }

        return res.status(200).json({ ok: true, broadcast: false });
      }

      // ---- Broadcast: no targetId given -> send to every known user ----
      const allUsers = await db.collection('users').find({}, { projection: { telegramId: 1 } }).toArray();

      // Fire all sends concurrently. Telegram will rate-limit a fraction of
      // these on large user bases (~30 msgs/sec) - failures are counted, not
      // fatal, so a big broadcast still finishes and reports how many landed.
      // NOTE: this function also has a maxDuration cap (see vercel.json) - on a
      // very large user base, re-run the broadcast if "sent" < "totalUsers".
      const results = await Promise.allSettled(
        allUsers.map(u =>
          imageUrl
            ? sendPhoto(u.telegramId, imageUrl, text || '', { reply_markup: replyMarkup })
            : sendMessage(u.telegramId, text, { reply_markup: replyMarkup })
        )
      );

      const sent = results.filter(r => r.status === 'fulfilled' && r.value.ok).length;
      const failed = results.length - sent;

      return res.status(200).json({ ok: true, broadcast: true, totalUsers: allUsers.length, sent, failed });
    }

    return res.status(400).json({ ok: false, error: 'unknown_entity_or_method' });
  } catch (err) {
    console.error('admin/manage.js error:', err);
    return res.status(500).json({ ok: false, error: 'server_error' });
  }
};
