const { getDb } = require('../../lib/db');
const { verifyAdmin } = require('../../lib/auth');
const { sendMessage, sendPhoto } = require('../../lib/telegram');

module.exports = async (req, res) => {
  try {
    // initData comes as a query param on GET/DELETE, or in the JSON body on POST/PUT
    const initData = req.method === 'GET' || req.method === 'DELETE' ? req.query.initData : req.body.initData;
    const admin = verifyAdmin(initData);
    if (!admin) return res.status(401).json({ ok: false, error: 'unauthorized' });

    const db = await getDb();
    const entity = req.query.entity; // 'video' | 'task' | 'message'

    // ---------------- VIDEO: publish using the code generated by webhook.js ----------------
    if (entity === 'video' && req.method === 'POST') {
      const { title, thumbnail, code } = req.body;
      if (!title || !thumbnail || !code) {
        return res.status(400).json({ ok: false, error: 'missing_fields' });
      }

      const pending = await db.collection('pendingUploads').findOne({ code, used: false });
      if (!pending) return res.status(404).json({ ok: false, error: 'invalid_or_used_code' });

      const result = await db.collection('videos').insertOne({
        title,
        thumbnail,
        sourceChatId: pending.sourceChatId,       // admin's own DM chat with the bot
        sourceMessageId: pending.sourceMessageId,  // no channel involved anywhere
        unlockCount: 0,
        createdAt: new Date()
      });

      await db.collection('pendingUploads').updateOne({ code }, { $set: { used: true } });

      return res.status(200).json({ ok: true, videoId: result.insertedId });
    }

    if (entity === 'video' && req.method === 'DELETE') {
      const { ObjectId } = require('mongodb');
      await db.collection('videos').deleteOne({ _id: new ObjectId(req.query.id) });
      return res.status(200).json({ ok: true });
    }

    if (entity === 'video' && req.method === 'PUT') {
      const { ObjectId } = require('mongodb');
      const { id, title, thumbnail } = req.body;
      await db.collection('videos').updateOne(
        { _id: new ObjectId(id) },
        { $set: { title, thumbnail } }
      );
      return res.status(200).json({ ok: true });
    }

    // ---------------- TASK ----------------
    if (entity === 'task' && req.method === 'POST') {
      const { title, reward, taskType, link, channelId } = req.body;
      if (!title || reward == null || !taskType || !link) {
        return res.status(400).json({ ok: false, error: 'missing_fields' });
      }
      if (taskType === 'verified' && !channelId) {
        return res.status(400).json({ ok: false, error: 'channelId_required_for_verified' });
      }

      const result = await db.collection('tasks').insertOne({
        title, reward: parseFloat(reward), taskType, link, channelId: channelId || null,
        active: true, createdAt: new Date()
      });
      return res.status(200).json({ ok: true, taskId: result.insertedId });
    }

    if (entity === 'task' && req.method === 'DELETE') {
      const { ObjectId } = require('mongodb');
      await db.collection('tasks').updateOne({ _id: new ObjectId(req.query.id) }, { $set: { active: false } });
      return res.status(200).json({ ok: true });
    }

    // ---------------- LIST (for admin panel tables) ----------------
    if (entity === 'video' && req.method === 'GET') {
      const videos = await db.collection('videos').find({}).sort({ createdAt: -1 }).toArray();
      return res.status(200).json({ ok: true, videos });
    }
    if (entity === 'task' && req.method === 'GET') {
      const tasks = await db.collection('tasks').find({}).sort({ createdAt: -1 }).toArray();
      return res.status(200).json({ ok: true, tasks });
    }

    // ---------------- CUSTOM MESSAGE TO A SPECIFIC USER ----------------
    // Sends text (or an image + caption) to one Telegram user, with a single
    // button underneath. The button's label is whatever the admin typed, but
    // its target is ALWAYS the bot's own Mini App (APP_URL) — clicking it
    // opens the web app directly, it never points anywhere else.
    if (entity === 'message' && req.method === 'POST') {
      const { targetId, text, imageUrl, buttonText } = req.body;
      if (!targetId || !text || !buttonText) {
        return res.status(400).json({ ok: false, error: 'missing_fields' });
      }

      const targetUser = await db.collection('users').findOne({ telegramId: String(targetId) });
      if (!targetUser) {
        return res.status(404).json({ ok: false, error: 'user_not_found' });
      }

      const appUrl = process.env.APP_URL;
      const replyMarkup = {
        inline_keyboard: [[
          { text: buttonText, web_app: { url: appUrl } }
        ]]
      };

      const result = imageUrl
        ? await sendPhoto(targetId, imageUrl, text, { reply_markup: replyMarkup })
        : await sendMessage(targetId, text, { reply_markup: replyMarkup });

      if (!result.ok) {
        return res.status(500).json({ ok: false, error: 'send_failed', detail: result.description });
      }

      return res.status(200).json({ ok: true });
    }

    return res.status(400).json({ ok: false, error: 'unknown_entity_or_method' });
  } catch (err) {
    console.error('admin/manage.js error:', err);
    return res.status(500).json({ ok: false, error: 'server_error' });
  }
};
